// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PMS_Net.Data;

#nullable disable

namespace PMS_Net.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("PMS_Net.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Project Breeze"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Command Program"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Project Point"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Project Mecha"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Program Pad"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Project Synergy"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Dynamic Program"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Project Zenen"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
